blank_issues_enabled: false
contact_links:
  - name: Discord Server
    url: https://discord.gg/sKeVmR3/
    about: Please ask and answer support questions here.
  - name: XLabsProject Website
    url: https://xlabs.dev/
    about: The official website.